name: OpenTofu CI (Plan / Apply)

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - main

env:
  INFRA_DIR: infra

concurrency:
  group: "opentofu-${{ github.ref }}"    # ensures runs for the same ref cancel previous
  cancel-in-progress: true

jobs:
  plan:
    # Run for non-main pushes and for PRs
    if: ${{ github.ref != 'refs/heads/main' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Login to Azure (Service Principal)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Init backend and Plan
        working-directory: ${{ env.INFRA_DIR }}
        env:
          TFSTATE_RG: ${{ secrets.AZURE_STATE_RG }}
          TFSTATE_SA: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          TFSTATE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
          TFSTATE_KEY: "plans/${{ github.sha }}.tfstate"
        run: |
          tofu init \
            -backend-config="resource_group_name=${TFSTATE_RG}" \
            -backend-config="storage_account_name=${TFSTATE_SA}" \
            -backend-config="container_name=${TFSTATE_CONTAINER}" \
            -backend-config="key=${TFSTATE_KEY}" \
            -backend-config="access_key=${AZURE_STORAGE_ACCESS_KEY}"

          tofu plan -out=plan.tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: plan-${{ github.ref }}-${{ github.sha }}
          path: ${{ env.INFRA_DIR }}/plan.tfplan

  apply:
    # Run only on main branch pushes (will do init, plan, apply)
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    # do NOT declare `needs: plan` since plan is skipped on main; keep independent
    steps:
      - uses: actions/checkout@v4

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Login to Azure (Service Principal)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Init, Plan and Apply (main)
        working-directory: ${{ env.INFRA_DIR }}
        env:
          TFSTATE_RG: ${{ secrets.AZURE_STATE_RG }}
          TFSTATE_SA: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          TFSTATE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
          TFSTATE_KEY: "prod.tfstate"
        run: |
          tofu init \
            -backend-config="resource_group_name=${TFSTATE_RG}" \
            -backend-config="storage_account_name=${TFSTATE_SA}" \
            -backend-config="container_name=${TFSTATE_CONTAINER}" \
            -backend-config="key=${TFSTATE_KEY}" \
            -backend-config="access_key=${AZURE_STORAGE_ACCESS_KEY}"

          # plan (so the log shows what will change) and then apply exactly that plan
          tofu plan -out=prod.tfplan
          tofu apply -auto-approve prod.tfplan
