name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: Initialize OpenTofu
        run: tofu init

      - name: Plan
        if: github.ref != 'refs/heads/main'
        run: tofu plan

      - name: Apply
        if: github.ref == 'refs/heads/main'
        run: tofu apply -auto-approve
